#!/bin/sh

if [[ $(playerctl status) != "Playing" ]]
then 
    echo $(playerctl status); 
    
else 
    if [[ "$1" == "--main" ]]; then
	    echo $(playerctl metadata --format "{{ artist }} - {{ title }}");
    elif [[ "$1" == "--album" ]]; then
        echo $(playerctl metadata --format "{{album}}");
    elif [[ "$1" == "--albumCover" ]]; then
        echo $(playerctl metadata mpris:artUrl);
    fi
fi